---
deployment:
  tasks:
    - export DEPLOYPATH=/home/demaumbe/repositories/demandcapture
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
