---
deployment:
  tasks:
    - export DEPLOYPATH=/home/demaumbe/appointments.demandcapture.com/
    - npm install
    - npm run build
    - /bin/cp -R build/* $DEPLOYPATH
    - chmod -R 755 $DEPLOYPATH
